### ISSUE TITLE
Referencing a token in the URL fails to fetch values from the Nightscout server

### ISSUE THREAD

**Issue by mdean0** [HanSolo/Gluco-Tracker#15]
When I define my Nightscout server URL with a token - for example:

https://myurl.herokuapp.com/?token=xx-123456

Gluco-Tracker fails to get any data. When I make the site publicly readable and define:

https://myurl.herokuapp.com

Values are fetched as expected. Can this be fixed so I dont have to make my site publicly readable?

Thanks again for all your efforts!

iphone Xr, 15.2.1

**Comment by HanSolo** [comment]
Good point, will check that. We only use the public url but you are right, it should also work with the token, will take a look. Thanks for thr heads-up 👍🏻

**Comment by HanSolo** [comment]
Do you think you could provide me a url with a working token so that I can use it for testing?

**Comment by mdean0** [comment]
Happy to set one up for up for you to use. Do you mind giving me your email address, Ill send it there?

**Comment by HanSolo** [comment]
han dot solo at mac dot com 😁

**Comment by HanSolo** [comment]
Did you send something? Did not receive anything yet.

**Comment by mdean0** [comment]
Apologies for the delay - just emailed the URL with a token.

**Comment by HanSolo** [comment]
Does it work with the latest version?

**Comment by mdean0** [comment]
Hi Gerrit - confirmed! I see the token field in the latest release of the app. I turned on the token requirement on Nightscout without configuring a token in the app to confirm no data was flowing to the app, then added the token into the app and started seeing updated data there.

Thanks again, your efforts are really appreciated. Nothing like seeing that large widget on the home screen  of my phone!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
