### ISSUE TITLE
Gluroo long api

### ISSUE THREAD

**Issue by Cheun1** [HanSolo/Gluco-Tracker#18]
Hello .
First thank you for this app.
 Can you work to add long api , like gluroo....(gluroo give us an url like NS , but the api is large , with gluroo we can use Nightguard and all others apps DIY )

thank you .

**Comment by Cheun1** [comment]
Yes with pleasure , but i do not understand your the syntaxe of your email .

**Comment by HanSolo** [comment]
well the dot is the . and the at is the @ as simple as that :)

**Comment by Cheun1** [comment]
Done

**Comment by Cheun1** [comment]
Thank you solved , just put Gluroo API on token line .
