### ISSUE TITLE
Values fixed in mg/dl

### ISSUE THREAD

**Issue by aliswalker** [HanSolo/Gluco-Tracker#6]
New install, values loading from NS however values display in mg/dl. Server set to mmol/l and both in-app settings changed to mmol/l.

Also:

-Notifications set to off for all 4 types, yet still receiving notifications

-Ranges are too precise to set in mmol/l (e.g. 8.020 instead of 8 or 7.9), the ranges are also not wide enough ie highest low/normal figure is 4.385

(Happy to split these into different issues)

**Comment by HanSolo** [comment]
- If the NS server is set to mmol/l, setting both switches to mmol/l in the app should do or do you still see mg/dl then?
- You cannot switch of notifications for too low and too high values. Here you just can switch of the sound
- I only use mg/dl and simply converted the mg/dl values to mmol/l. So one decimal is enough when using mmol/l?

**Comment by HanSolo** [comment]
So we usually have the normal range for our son between 70 - 140 mg/dl which should be between 4.4 - 8.9 mmol/l if I'm correct. Would it help to set the highest low normal to 90 mg/dl (5.0 mmol/l)?

**Comment by aliswalker** [comment]
> - If the NS server is set to mmol/l, setting both switches to mmol/l in the app should do or do you still see mg/dl then?
> 
> - You cannot switch of notifications for too low and too high values. Here you just can switch of the sound
> 
> - I only use mg/dl and simply converted the mg/dl values to mmol/l. So one decimal is enough when using mmol/l?

Yes, still mg/dl (even after restarting app and waiting an hour). Lots of values and the graph populated, just incorrect unit and a big black space on the right side of the screen (as e.g. 180.0 is too long to fit)

Ah, maybe that could be a feature request as I have 2 phones, a watch and numerous apps providing alerts already?

Yes please 1 DP is ideal

And yes 5 mmol/l is probably what I'd set for low normal

**Comment by HanSolo** [comment]
Ok, will take a look at it tomorrow, thx for reporting 👍🏻

**Comment by HanSolo** [comment]
Ok so I've switched my own server to mmol/l and it seems that the api always offers values in mg/dl. If you leave the server unit to mg/dl and switch the unit to mmol/l you should see the correct value. I think I will remove the server unit setting from the app.

**Comment by HanSolo** [comment]
So I've remove the server unit from the settings, made it possible to disable too high/too low notifications, fixed the ranges and set the decimal to 1.
If you are interested I could add you to Testflight so that you can test the beta version. Therefor I would need your email address, you can send it to han dot solo dot gg at gmail dot com

**Comment by HanSolo** [comment]
Should be fixed
