### ISSUE TITLE
Background refresh 

### ISSUE THREAD

**Issue by flopezsanroman** [HanSolo/Gluco-Tracker#7]
It seems background refresh is not working in gluco-tracker widget. I have to open the app and then it refreshes la glucose value. But it doesn’t do it automatically and maintains this value until I open again GlucoTracker

**Comment by HanSolo** [comment]
It is updating the widgets but unfortunately not in the requested interval. The operating system decides when it's the best moment to run the background task for the update. I'm currently deploying another beta version in Testflight which has uses a different approach to fetch the latest nightscout values in a shorter interval. At the moment the widget on my iPhone will be updated around every 5-10 minutes but it really depends on the usage it seems

**Comment by flopezsanroman** [comment]
Thanks!! Please send me an invitation to test beta version :)))

Fernando Lopez

**Comment by HanSolo** [comment]
I figured out that it was faster to release it directly. It seems Apple is busy approving apps for Testflight these days. So please find version 2.6 in the app store. It‘s definitely updating the widgets but unfortunately not in the given intervals. I see now updates in the range of up to 15 min.

**Comment by HanSolo** [comment]
Should be fixed, keep in mind that the frequency of updates depends on the usage if the app. Apple uses some AI to decide when it will execute the background tasks.
