### ISSUE TITLE
Doesn’t download any readings

### ISSUE THREAD

**Issue by jonfawcett** [HanSolo/Gluco-Tracker#8]
Doesn’t actually do anything for me after entering NS url. Feel free to DM me. I’m the dev behind Loop Follow, so I’ve coded NS download and processing and am happy to help test it in debugger to resolve whatever the issue is.

**Comment by HanSolo** [comment]
Ok that‘s not good. Would you send me the url so that I can take a look at the problem? If so please mail it to han dot solo dot gg at gmail dot com
I saw such problems when people use specific add on‘s that send additional data in the json.

**Comment by MarkFrankus** [comment]
Hi - I’m the same; URL added and no updates. Happy to email over too if that is OK. Thanks

**Comment by HanSolo** [comment]
Sure, just mail it to me and I‘ll take a look. Most of the times it‘s parameters or formats I‘m not aware of.

**Comment by HanSolo** [comment]
I think I found the problem, will release another version tomorrow...so stay tuned

**Comment by mivait** [comment]
Hi, is it possible to use access token in NS url. If I use ?token=***** in url I'll get no data

**Comment by HanSolo** [comment]
No for the api access you don't need the token, just the url

**Comment by HanSolo** [comment]
Should be fixed
